name: Feature Request

about: Suggest an idea for this project

title: "[Feature Request] "

labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        **Description:**
        <!-- A clear and concise description of the feature you\'re proposing. -->

        **Use Case:**
        <!-- Describe the use case for this feature. -->

        **Possible Implementation:**
        <!-- If you have suggestions on how to implement this feature, provide them here. -->
    validations:
      required: true
