name: AutoGen Issue
title: "[AutoGen]: "
body: |
  ---
  ## Please fill out this template completely to help us resolve your issue quickly.

  **Title:** {{title}}

  **Type of issue:**

  * {{type}}

  **Description:**

  {{description}}

  **Version:**

  * AutoGen version: {{autogen_version}}
  * Operating system: {{os}}
  * Python version: {{python_version}}

  **Additional information:**

  {{additional_information}}

  **Labels:**

  {{labels}}

  **Assignee:**

  {{assignee}}

  ---

inputs:
  title:
    type: text
    label: Title
    required: true
  type:
    type: dropdown
    label: Type of issue
    options:
      - Bug report
      - Feature request
      - Other (please specify)
    default: 0
    required: true
  description:
    type: textarea
    label: Description
    required: true
  autogen_version:
    type: text
    label: AutoGen version
    required: true
  os:
    type: text
    label: Operating system
    required: true
  python_version:
    type: text
    label: Python version
    required: true
  additional_information:
    type: textarea
    label: Additional information
  labels:
    type: checkboxes
    label: Labels
    options:
      - bug
      - feature
      - documentation
      - other
  assignee:
    type: text
    label: Assignee

validations:
  required:
    - title
    - type
    - description
    - autogen_version
    - os
    - python_version
