name: Question/Ask

about: Ask a question or request assistance

title: "[Question/Ask] "

body:
  - type: markdown
    attributes:
      value: |
        **Description:**
        <!-- A clear and concise description of your question or request for assistance. -->

        **Context:**
        <!-- Provide any relevant context or background information. -->

        **Environment:**
        - AutoGen Version: <!-- Specify the AutoGen version (e.g., v2.1.0) -->
        - Operating System: <!-- Specify the OS (e.g., Windows 10, Ubuntu 20.04) -->
        - Python Version: <!-- Specify the Python version (e.g., 3.8) -->

        **Additional Information:**
        <!-- Include any additional information that might be helpful for understanding your question. -->
